#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Setting wayland environment variables for graphical applications launched outside of Hyprland (like from TTYs or systemd services)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start graphical-session.target

# Set wallpapers with swww (swaybg/wallpaper client) at startup
exec-once = ~/.config/hypr/bin/wallpaper-manager -interval 3600 > /tmp/wallpaper-manager.log 2>&1
#exec-once = awww img ~/.config/hypr/wallpapers/dp-1.jpg --outputs "DP-1"
#exec-once = awww img ~/.config/hypr/wallpapers/dp-3.png --outputs "DP-3"

# wl-clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
