#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Setting wayland environment variables for graphical applications launched outside of Hyprland (like from TTYs or systemd services)
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start graphical-session.target

# Set wallpapers with swww (swaybg/wallpaper client) at startup
exec-once = swww img ~/.config/hypr/wallpapers/midnight_2560.jpg --outputs "DP-1"
exec-once = swww img ~/.config/hypr/wallpapers/retro_legends_slices_4_1080x1920.png --outputs "DP-3"

# launch a kitty isntance with class "scratchpad" to be used as a scratchpad workspace
exec-once = kitty --class scratchpad

# wl-clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
